#!/bin/bash
#
# Take new files from a list of directories, give them show titles and content, the "podcast" genre, and FTP them up to the Wordpress site

FTP_SERVER="${PU_FTP_SERVER:-radiofreepalmer.org}"
FTP_DIR="${PU_FTP_DIR:-html/wp-content/uploads/mp3-to-post}"
FTP_USER="${PU_FTP_USER:-mikecski}"
MID3_PATH="${PU_MID3_PATH:-/usr/local/bin}"
LOCALDIR="${PU_LOCALDIR:-/rfpserver}"
TEMP_DIR="${PU_TEMP_DIR:-temp}"
PODCAST_GENRE_DEFAULT="${PU_PODCAST_GENRE_DEFAULT:-podcast}"     # how to tag mp3s for the podcast blog feed
MARKER_COMMENT="${PU_MARKER_COMMENT:-podcastuploaded}"  #Comment that signals file looked at
START_AFTER_DATE="${PU_START_AFTER_DATE:-2016-03-01}"
PODCAST_DATA_FILE="${PU_PODCAST_DATA_FILE:-podcast_data.txt}"

if [ -d "${MID3_PATH}" ] && [[ ":$PATH:" != *":$MID3_PATH:"* ]]; then
    PATH="${PATH:+"$PATH:"}$MID3_PATH"
fi

# Podcast metadata array
# podcasts[directory]=title|description|genre
# read from PODACAST_DATA_FILE with lines: directory|title|description|genre (wordpress category)

declare -A podcasts

while IFS='' read -r line || [[ -n "$line" ]]; do
    echo "Reading podcast data: $line"
    IFS="|"; read -r dir data <<< "${line}"
    podcasts["${dir}"]="${data}"
done < "${PODCAST_DATA_FILE}"

# podcasts["Radio Book Club"]="Radio Book Club|Latest book discussion moderated by Judy Gette|Radio Book Club"
# podcasts["Sports Scene with Tim Rockey"]="Sports Scene with Tim Rockey|Local sports discussion with Tim Rockey|Sports Scene with Tim Rockey"
# podcasts["YouAutoKnow"]="You Auto Know|Weekly show on auto care and repair, hosted by Tobi Klunder-Edmonds of Edmonds Auto in Palmer|You Auto Know"
# podcasts["Valley Edition"]="Valley Edition|Michael Chmielewski moderates a panel on current issues in the Valley|Valley Edition"
# podcasts["MorningShowInterviews(New)"]="Morning Show Interviews|Interviews from the Mike and Friends morning show|Morning Show Interviews"
# podcasts["Glacier Review"]="Glacier Review|Current events, science, and art from Glacier View with Joseph Davis|Glacier Review"
# podcasts["Citizen Lobbyist 2016:17"]="Citizen Lobbyist|Discussion of local, borough, and state politics|Citizen Lobbyist"
# podcasts["Dog Talk Radio:Mushing Radio"]="Dog Talk Radio|Interviews the top names in the sport of dog sledding along with our annual nightly coverage of the Iditarod each March|Dog Talk Radio"
# podcasts["Inside the City"]="Inside the City|Discussions and interviews with employees and administrators from the city of Palmer|Inside the City"
# podcasts["AG Matters"]="Ag Matters|Farming in Alaska with Amy Petit from Alaska Farmland Trust|Ag Matters"

cd ${LOCALDIR}

for dir in "${!podcasts[@]}"
do
  echo "Looking for directory \"${dir}\""
  if [ -d "${dir}" ]; then
    cd "${dir}"
    IFS="|"; read -ra podcast_info <<< "${podcasts[${dir}]}"
    if [ -n "${podcast_info[2]}" ]
    then
      podcast_genre="${podcast_info[2]}"
    else
      podcast_genre="${PODCAST_GENRE_DEFAULT}"
    fi
    echo "Found ${podcast_genre}"
    touch timestamp -d ${START_AFTER_DATE}
    find . -newer timestamp -name "*.mp3" | while read fname; do
      fname=$(basename "${fname}")
      echo Looking at ${fname}
      if ! mid3v2 -l "${fname}" | grep -q ${MARKER_COMMENT}; then
        echo New file found: ${fname}
        filedata=`stat -c%y "${fname}"`
        IFS=" "; read -ra filedata_array <<< "${filedata}"
        filedate=`date -d ${filedata_array[0]} +%m/%d/%Y`
        cp "${fname}" "${TEMP_DIR}"
        mid3v2 --delete-frames=COMM "${TEMP_DIR}/${fname}"
        mid3v2 -g "${podcast_genre}" -t "${podcast_info[0]} ${filedate}" -c "${podcast_info[1]}" "${TEMP_DIR}/${fname}"
#        sftp ${FTP_USER}@${FTP_SERVER}:${FTP_DIR} <<< $"put \"${TEMP_DIR}/${fname}\""
        # scp -c blowfish "${TEMP_DIR}/${fname}" ${FTP_USER}@${FTP_SERVER}:${FTP_DIR}
        scp "${TEMP_DIR}/${fname}" ${FTP_USER}@${FTP_SERVER}:${FTP_DIR}
        mid3v2 -c "${MARKER_COMMENT}" "${fname}"
        rm "${TEMP_DIR}/${fname}"
      fi
    done
    cd ${LOCALDIR}
  fi
done
