#!/bin/bash
#
# Go to prx and download the latest shows SubAuto has staged on their FTP for us

FTP_SERVER="${PD_FTP_SERVER:-kvrf.prxtransfer.org}"
FTP_USER="${PD_FTP_USER:-username}"
FTP_PASSWORD="${PD_FTP_PASSWORD:-password}"
LOCALDIR="${PD_LOCALDIR:-/rfpserver}"
SHOW_DATA_FILE="${PD_SHOW_DATA_FILE:-show_data.txt}"
NOTIFY_EMAIL="${PD_NOTIFY_EMAIL:-tim@eschers.com}"

# Show metadata array
# shows[ftp_directory]=show_name|local_subdirectory
# read from SHOW_DATA_FILE with lines: show_name|ftp_directory|local_subdirectory

declare -A shows

while IFS='' read -r line || [[ -n "$line" ]]; do
    echo "Reading show data: $line"
    IFS="|"; read -r show dirs <<< "${line}"
    shows["${show}"]="${dirs}"
done < "${SHOW_DATA_FILE}"

cd ${LOCALDIR}

wget_opts='--user="${FTP_USER}" --password="${FTP_PASSWORD}"'
result_mesg="PRX download started"

for show in "${!shows[@]}"
do
  IFS="|"; read -r subdir ftpdir <<< "${shows[${show}]}"
  echo "Looking for directory \"${LOCALDIR}/${subdir}\""
  if [ -d "${LOCALDIR}/${subdir}" ]
  then
    cd "${LOCALDIR}/${subdir}"
    num_downloaded=$(wget -N ${wget_opts} ftp://${FTP_SERVER}/${ftpdir}/* 2>&1 | grep -c 'saved')
    if (( num_downloaded > 1 ))
    then
      mesg="${num_downloaded} files downloaded to ${LOCALDIR}/${subdir} for ${show}"
    else
      mesg="No files downloaded for ${show}"  
    fi
    echo $mesg
    result_mesg="${result_mesg}\n${mesg}"
  else
    mesg="Cannot find local directory \"${LOCALDIR}/${subdir}\""
    echo $mesg
    result_mesg="${result_mesg}\n${mesg}" 
  fi
done

echo ${result_mesg}

if [ -n ${NOTIFY_EMAIL} ]
then
  echo "${result_message}" | mail -s "PRX Download" ${NOTIFY_EMAIL}
fi
